### ISSUE TITLE
Can't activate the addon on 2.91 or 2.83

### ISSUE THREAD

**Issue by ludogemma** [BlenderDefender/io_voodoo_tracks#6]
**Describe the bug**
can't activate

**To Reproduce**
normal way to install addon

**Expected behavior**
Can't activate the addon

**Screenshots**
![voodoo](https://user-images.githubusercontent.com/67376781/100525178-df031300-31be-11eb-906b-7bffcdc899bc.png)

**Desktop (please complete the following information):**

- OS: mac osx High Sierra
- Blender Version 2.91 and 2.83.9

**Comment by BlenderDefender** [comment]
@ludogemma It looks like the zip is named <io_voodoo_tracks-1>, have you tried to rename it (remove the -1)? Blender produces weird errors sometimes if the folder/zip isn't named properly.

**Comment by ludogemma** [comment]
hi i renamed the zip file "io_voodoo_tracks.zip" but continue to give same error.

**Comment by ludogemma** [comment]
nevermind i fixed .. i just unzipped the file .. renamed the folder and zipped again and installed now works!
thanks alot!

**Comment by BlenderDefender** [comment]
You're welcome :) 👍
